Operatorhub test
Apicurio/apicurio-qe pull request #88
Opened 2021-08-31 11:20 UTC by AnetaCadova

2021-08-31 11:29 UTC, mmuzikar commented on src/test/java/apicurito/tests/steps/ConfigurationOCPSteps.java
> +//            "openshift-marketplace");
These lines can be deleted or executed `if (TestConfiguration.namespaceCleanupAfter())`

2021-09-03 15:04 UTC, mmajerni requested changes

2021-09-03 15:04 UTC, mmajerni commented on src/test/resources/features/notUiFeatures/operatorhubTest.feature
> +  @operatorhub-upgrade
I would change the test. This is not testing upgrade in the way we want to.  We want to install Apicurito from operatorhub (operator and UI+generator) (Basically first test^^) After that we want to upgrade operator and check that all resources are updated operator UI and generator all pod are from new images.

2021-09-06 08:53 UTC, mmajerni commented on src/test/java/apicurito/tests/configuration/TestConfiguration.java
> +    public static final String APICURITO_OPERATOR_PREVIOUS_METADATA_URL = "apicurito.config.operator-prev-version.metadata.url";
Add this param to `ReleaseSpecificParameters` since it will be not changing during testing one version of Apicurito.

2021-10-01 13:32 UTC, mmajerni commented
merge, follow up soon.

2021-10-01 13:33 UTC, merged